version: "3.9"
services:
  keycutter:
    restart: always
    image: "hexploits/keycutter"
    networks:
      - keycutter-network
    ports:
      - "7314:7314"
    depends_on:
      - database
    environment:
      - KC_PORT=7314
      - KC_ENV=prod
      - KC_EMAIL_PROVIDER=ses
      - KC_EMAIL_SENDER=info@hexploits.com
      - KC_UI_ADMIN_USERNAME=operations
      - KC_UI_ADMIN_PASSWORD=operations
      - KC_LOGS_LOGIN_PERIOD=365
      - KC_LOGS_LOGIN_STRATEGY=delete
      - KC_LOGS_EVENTS_PERIOD=365
      - KC_LOGS_EVENTS=STRATEGY=delete
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY
      - AWS_SECRET_KEY=YOUR_SECRET
      - AWS_S3_BUCKET=keycutter
      - PG_HOST=database
      - PG_PORT=5432
      - PG_DATABASE=keycutter
      - PG_USERNAME=keycutter
      - PG_PASSWORD=SECURE_PASSWORD
      - JWT_TOKEN_SECRET=YOUR_SECURE_SECRET
      - JWT_TOKEN_EXPIRATION=86400

  database:
    restart: always
    image: "postgres"
    networks:
      - keycutter-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycutter
      - POSTGRES_DB=keycutter
      - POSTGRES_PASSWORD=SECURE_PASSWORD

networks:
  keycutter-network:
    driver: bridge