name: Sync Readme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: meeDamian/sync-readme@v1.0.6
      with:
        user: hexploits
        pass: ${{ secrets.DOCKER_PASSWORD }}
        slug: hexploits/keycutter
        description: true
